CREATE TABLE types (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE companies(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50),
  type_id INT,
  FOREIGN KEY(type_id) REFERENCES types(id),
  country VARCHAR(50),
  tva VARCHAR(50),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE invoices(
  id INT AUTO_INCREMENT PRIMARY KEY,
  ref VARCHAR(50),
  id_company INT,
  FOREIGN KEY(id_company) REFERENCES companies(id),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE contacts(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50),
  company_id INT,
  FOREIGN KEY(company_id) REFERENCES companies(id),
  email VARCHAR(50),
  phone VARCHAR(50),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE roles(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE permissions(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE roles_permission(
  id INT AUTO_INCREMENT PRIMARY KEY,
  permission_id INT,
  FOREIGN KEY(permission_id) REFERENCES permissions(id),
  role_id INT,
  FOREIGN KEY(role_id) REFERENCES roles(id)
);

CREATE TABLE users(
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(50),
  role_id INT,
  FOREIGN KEY(role_id) REFERENCES roles(id),
  last_name VARCHAR(50),
  email VARCHAR(50),
  password VARCHAR(50),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP
);
